# Enable generic I2C API
CONFIG_I2C=y

# Optional – better debug output
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_DEFERRED=y

# Optional: bridge printk calls to logger
CONFIG_LOG_PRINTK=y